language: node_js
node_js:
  - 10

# travis ci is configured by adding a file named .travis.yml to the root of the directory of the repository repository. this file specifies the programming language used, the desired building and testing environment (including dependencies which must be installed before the software can be built and tested), and various other parameters.